name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the hello-world Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u guruprasadsingirikonda --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}    
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/guruprasadsingirikonda/my-nginx-image:latest
          
    - name: pushing the image  
      run: docker push ghcr.io/guruprasadsingirikonda/my-nginx-image:latest
      
      
